models:
  - name: fct_customer_orders
    description: Transformed data representing customer orders
    columns:
      - name: order_id
        description: '{{ doc("order_id") }}'
        tests:
          - unique
          - not_null
      - name: customer_id
        description: '{{ doc("customer_id") }}'
      - name: order_place_at
        description: '{{ doc("order_place_at") }}'
      - name: order_status
        description: '{{ doc("order_status") }}'
      - name: total_amount_paid
        description: '{{ doc("total_amount_paid") }}'
      - name: payment_finalized_date
        description: '{{ doc("payment_finalized_date") }}'
      - name: customer_first_name
        description: '{{ doc("customer_first_name") }}'
      - name: customer_last_name
        description: '{{ doc("customer_last_name") }}'
      - name: transaction_seq
        description: '{{ doc("transaction_seq") }}'
      - name: customer_sales_seq
        description: '{{ doc("customer_sales_seq") }}'
      - name: nvsr
        description: '{{ doc("nvsr") }}'
      - name: customer_lifetime_value
        description: '{{ doc("customer_lifetime_value") }}'
      - name: fdos
        description: '{{ doc("fdos") }}'